name: C++ CI with Test Coverage

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libopencv-dev libgtest-dev p7zip-full lcov g++ gcc

    - name: Create Build Directory
      run: mkdir build

    - name: CMake Generate
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build Project
      run: cmake --build build

    - name: Run Tests
      run: ./build/runTests.so

    - name: Capture LCOV coverage report
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info # Exclude system libraries
        lcov --list coverage.info

    - name: Upload coverage to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage_report

    - name: Archive coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.info
