name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libopencv-dev libgtest-dev p7zip-full lcov

    - name: Create Build Directory
      run: mkdir build

    - name: CMake Generate (Debug mode)
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build Project
      run: cmake --build build

    - name: Run Tests
      run: ./build/runTests.so

    - name: Gather Coverage Data
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.filtered.info

    - name: Display Coverage Report
      run: genhtml coverage.filtered.info --output-directory out

    - name: Archive Coverage Reports
      uses: actions/upload-artifact@v2
      with:
        name: coverage-reports
        path: out
